INSERT INTO events (title, link, description, pub_date, event_start_date, event_end_date, location, image_url) VALUES 
('Spring Semester Begins. Tuition and Fee Payment Due', '/e/4974', '', 'January 2, 2025', 'January 2, 2025', null, '','' ),
('Law Intensive Trial Practice (ITP)', '/e/5309', '', 'Jan  2, 2025', 'Jan  2, 2025', 'Jan 11, 2025', '','' ),
('Winter Residency', '/e/4971', '', 'Jan  2, 2025', 'Jan  2, 2025', 'Jan 12, 2025', '','' ),
('Fall semester final grades due in Registrar''s Office at 8:00 a.m.', '/e/4968', '', 'January 3, 2025', 'January 3, 2025', null, '','' ),
('HFMA First Friday Salem Art Walk', '/e/5946', 'Start your First Friday Art Walk at the Hallie Ford Museum of Art and get ready for an evening of fun and art in Salem!', 'January 3, 2025', 'January 3, 2025', null, 'Start your First Friday Art Walk at the Hallie Ford Museum of Art and get ready for an evening of fun and art in Salem!','https://d1tvaw2qn8888b.cloudfront.net/cal-00aa554f-9840-49ed-accd-c9c7ced0c2dc/square.jpg' ),
('Wintersession', '/e/4970', '', 'Jan  6, 2025', 'Jan  6, 2025', 'Jan 10, 2025', '','' ),
('Dinner is First Board Meal at Salem Campus', '/e/5715', '', 'January 8, 2025', 'January 8, 2025', null, '','' ),
('New Student Move In Day - Salem Campus', '/e/5712', '', 'January 8, 2025', 'January 8, 2025', null, '','' ),
('Residential Facilities Open for Spring 2025 - All Campuses', '/e/5525', 'Residential facilities reopen at 9:00 am for Spring semester, 2025.', 'Jan 10, 2025', 'Jan 10, 2025', 'Jan 11, 2025', 'Residential facilities reopen at 9:00 am for Spring semester, 2025.','' ),
('Camerata PYP featuring Llewellyn Sanchez-Werner', '/e/6374', 'Camerata PYP returns with a unique program - a “recital for piano and orchestra” - that blends the elegance of classical traditions with vibrant modern compositions, featuring renowned guest Llewellyn SÁNCHEZ-WERNER, piano, and conducted by Musical Director David Hattner.', 'January 12, 2025', 'January 12, 2025', null, 'Hudson Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-97b737e1-c426-42da-8cba-7c72794c4501/square.jpg' ),
('Hallie Ford: Spring Semester Begins. Tuition and Fee Payment Due', '/e/6435', '', 'January 13, 2025', 'January 13, 2025', null, '','' ),
('Spring Semester Begins. Tuition and Fee Payment Due', '/e/4973', '', 'January 13, 2025', 'January 13, 2025', null, '','' ),
('Last day to add/drop or choose Audit (AUD) grading for full semester and first half-semester classes (5 p.m. deadline)', '/e/4978', '', 'January 15, 2025', 'January 15, 2025', null, '','' ),
('A Biedermeier Evening', '/e/6360', 'Professors Emma Cowell and Esteban Zuniga share the music of Biedermeier.', 'January 16, 2025', 'January 16, 2025', null, 'Cone Chapel','https://d1tvaw2qn8888b.cloudfront.net/cal-94adf283-c80f-458b-89d2-3f0c7762a3ac/square.jpg' ),
('QUAD Center Opening & Ribbon Cutting', '/e/6386', 'The official opening of the QUAD Center for the spring semester will feature a brief ribbon cutting with cookies and tea.', 'January 17, 2025', 'January 17, 2025', null, '224','https://d1tvaw2qn8888b.cloudfront.net/cal-620c3d52-2945-43d4-ab70-7a10900534c3/square.jpg' ),
('Panhellenic Open House', '/e/6369', 'Join Willamette’s sororities in an evening dedicated to meeting new people, hands-on activities, and seeing what sorority life is all about!', 'January 17, 2025', 'January 17, 2025', null, 'Main Living room and dining room.','' ),
('Community Art Build at PNCA with Don''t Shoot PDX & the ACLU', '/e/6378', 'On January 18, join Don’t Shoot Portland at the Pacific Northwest College of Art
for an art build ahead of Reclaim MLK March! Create meaningful art, learn from local organizers with
resources and meet your Portland neighbors to cultivate community and impact.', 'January 18, 2025', 'January 18, 2025', null, 'Shipley-Collins Medatheque & Printmaking Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-b8463d09-383f-4dc6-bb3b-2ccaf08fb816/square.jpg' ),
('Martin Luther King Jr. Holiday (University Closed)', '/e/4976', '', 'January 20, 2025', 'January 20, 2025', null, '','' ),
('Academic Success Workshop', '/e/6370', 'Willamette College invites undergraduate students on the Salem Campus to attend an academic success workshop.', 'January 21, 2025', 'January 21, 2025', null, '301','' ),
('Meet the New Career Advisor for the Renjen/Deloitte Pathways Program', '/e/6385', 'This is an introductory event for students to get to know Daniel Arellano, the new career advisor for the Rejen/Deloitte Pathways Program and for Daniel to get to know students.', 'January 22, 2025', 'January 22, 2025', null, 'Renjen Center (E&E)','' ),
('ASWU Treasurer Office Hours', '/e/6408', 'ASWU Treasurer Sophia “Stevie” Bergstrom has office hours to provide an opportunity for students to come by to ask questions, share concerns or ideas, or even just say hi! If these times don’t work for you, you can always reach the ASWU team by email: aswu@willamette.edu or contact Stevie using treasurer@willamette.edu.', 'January 22, 2025', 'January 22, 2025', null, 'The Bistro','' ),
('The Hanni Student Scholar Award', '/e/6440', 'Students!
Apply to present your research or project to the Willamette Institute for Continued Learning', 'Jan 23, 2025', 'Jan 23, 2025', 'Jan 30, 2025', 'Students!
Apply to present your research or project to the Willamette Institute for Continued Learning','' ),
('TechBytes -The Future of Learning: AI, Gamification, Social Media, and Inquiry-Based Learning', '/e/6394', 'TechBytes is a weekly department event for students and faculty gather to discuss various topics related to computing. There is typically a set topic featuring members of Willamette’s staff, faculty, and students as speakers. These topics range from career advice and uses of emerging technology to info sessions about relevant programs. Snacks and pizza are usually provided!', 'January 23, 2025', 'January 23, 2025', null, '102','https://d1tvaw2qn8888b.cloudfront.net/cal-8d4a43c7-e1a3-4d58-9834-14a60e401b92/square.jpg' ),
('Virtual Trivia', '/e/6382', 'Compete for prizes across multiple rounds of trivia against fellow members of the Willamette community!
Thursday, January 23, 2025
6:30 p.m. (PST)
The Zoom link will be shared the day before the event.', 'January 23, 2025', 'January 23, 2025', null, 'Compete for prizes across multiple rounds of trivia against fellow members of the Willamette community!
Thursday, January 23, 2025
6:30 p.m. (PST)
The Zoom link will be shared the day before the event.','' );

INSERT INTO events (title, link, description, pub_date, event_start_date, event_end_date, location, image_url) VALUES 
('ASWU Weekly Senate Meeting', '/e/6411', 'Join us for an engaging and productive ASWU Meeting! This is your chance to get involved, voice your opinions, and contribute to positive changes on our campus. ASWU Senate Meetings will be here every Thursday from 7-8pm @ Montag Den.', 'January 23, 2025', 'January 23, 2025', null, 'Montag Den','' ),
('Dining Plan Changes Due - Salem Campus', '/e/5527', 'Last day to change your dining plan for Spring 2025.', 'January 24, 2025', 'January 24, 2025', null, 'Last day to change your dining plan for Spring 2025.','' ),
('Succulents & Sisterhood', '/e/6383', 'Alpha Phi’s first recruitment event of the year!', 'January 24, 2025', 'January 24, 2025', null, '880 Mill Street','https://d1tvaw2qn8888b.cloudfront.net/cal-7e28e92c-f8a7-447f-bd60-acc4dad2eff9/square.jpg' ),
('ASWU Vice President Office Hours', '/e/6409', 'ASWU Vice President Sal Chapell has office hours to provide an opportunity for students to come by to ask questions, share concerns or ideas, or even just say hi! If these times don’t work for you, you can always reach the ASWU team by email: aswu@willamette.edu or contact Sal using aswu-vp@willamette.edu.', 'January 24, 2025', 'January 24, 2025', null, 'The Bistro','' ),
('Giddy Up with Alpha Chi!', '/e/6406', 'Play yard games, drink mocktails, and get to know Alpha Chi!', 'January 26, 2025', 'January 26, 2025', null, '880 Mill Street','' ),
('Hallie Ford: Last day to add/drop or choose Audit (AUD) grading for full semester and first half-semester classes (at 5 p.m.)', '/e/6436', '', 'January 27, 2025', 'January 27, 2025', null, '','' ),
('Last day to add/drop or choose Audit (AUD) grading for full semester and first half-semester classes (5 p.m. deadline)', '/e/4977', '', 'January 27, 2025', 'January 27, 2025', null, '','' ),
('Spring Activities Fair and Carnival in the UC', '/e/6363', 'An introduction to student clubs and organizations as well as the resources available in the University Center.', 'January 27, 2025', 'January 27, 2025', null, 'An introduction to student clubs and organizations as well as the resources available in the University Center.','' ),
('Almost Something', '/e/6443', 'A group exhibition of PNCA’s First Year MFA Candidates', 'Jan 28, 2025', 'Jan 28, 2025', 'Feb 18, 2025', 'B10 Gallery, 157 Gallery, Atrium Gallery','https://d1tvaw2qn8888b.cloudfront.net/cal-6d6d985a-f8e5-4206-a8a6-c395e0e95771/square.jpg' ),
('Academic Success Workshop', '/e/6371', 'Willamette College invites undergraduate students on the Salem Campus to attend an academic success workshop.', 'January 28, 2025', 'January 28, 2025', null, '301','' ),
('WU Stream: Last Lecture with the Provost Carol Long', '/e/6384', 'Carol S. Long is Willamette’s Provost and Senior Vice President. She helps to enhance collaboration among the schools of Willamette University and between student and academic affairs.Long first joined Willamette University as a Professor of English in 1972. In roughly 45 years of service to the institution, she has served as department chair, associate dean, dean of the College of Arts & Sciences, and finally as Provost and Senior Vice President.She will retire at the end of the school year, bringing to a close one of the most storied of Willamette careers.For those who had the good fortune of taking a class with Carol, and perhaps even more so for those who did not, we’re hosting her for one last lecture on Invisible Cities per Italo Calvino. The piece is a work of fiction imagining a conversation between an aged Kublai Khan and a young Marco Polo. Whether you’ve read it or not, you won’t want to miss Carol’s dive into this fascinating text.', 'January 28, 2025', 'January 28, 2025', null, 'For those who had the good fortune of taking a class with Carol, and perhaps even more so for those who did not, we’re hosting her for one last lecture on Invisible Cities per Italo Calvino. The piece is a work of fiction imagining a conversation between an aged Kublai Khan and a young Marco Polo. Whether you’ve read it or not, you won’t want to miss Carol’s dive into this fascinating text.','' ),
('Academic Success Workshop - Making Friends with Your Brain', '/e/6420', 'Unlock strategies for working with your brain’s unique quirks and capabilities. Learn practical tools to improve your academic experience.', 'January 29, 2025', 'January 29, 2025', null, '511','' ),
('Quad Cookie Social', '/e/6398', 'On January 29th from 4:30-6pm, the QUAD center will be hosting a cookie social where students can come and enjoy cookies.Come join us and eat cookies', 'January 29, 2025', 'January 29, 2025', null, '224','https://d1tvaw2qn8888b.cloudfront.net/cal-d75d90cd-a459-40ad-ba95-5de871c0140c/square.jpg' ),
('Academic Success Workshop - Making Friends with Your Brain', '/e/6421', 'Unlock strategies for working with your brain’s unique quirks and capabilities. Learn practical tools to improve your academic experience.', 'January 30, 2025', 'January 30, 2025', null, '511','' ),
('Dempsey Environmental Lecture: Dr. Suzanne Simard', '/e/6368', 'Annual Dempsey Environmental Lecture featuring Dr. Suzanne Simard', 'January 30, 2025', 'January 30, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-272ec256-d51e-4cc9-9a11-9c5a29a9f0a5/square.jpg' ),
('Mark & Melody Creative Writing Prizes at Willamette', '/e/6146', 'Submit one poem, one story, or one essay (15 pages maximum) between November 30, 2024 and January 31, 2025. Prizes announced mid-April.', 'January 31, 2025', 'January 31, 2025', null, 'Submit one poem, one story, or one essay (15 pages maximum) between November 30, 2024 and January 31, 2025. Prizes announced mid-April.','' ),
('Catalyst Info Session', '/e/6465', 'Short info sessions will be held for those interested in learning more about the Catalyst position in the Office of Civic Engagement. We offer opportunities to preform civic service, and promote education while building community bonds.', 'January 31, 2025', 'January 31, 2025', null, 'Collaboration Commons in the Office of Civic Engagement','' ),
('Willamette Day (183 Years)', '/e/4980', '', 'February 1, 2025', 'February 1, 2025', null, '','' ),
('Sexual Safety Kits with HIV Alliance', '/e/6407', 'Queer Student Union is working with HIV Alliance to build harm reduction and hygiene kits! Find comfort in community while helping out a great local organization.', 'February 1, 2025', 'February 1, 2025', null, '102','' ),
('Senior Recital: Jaylah Bennett', '/e/6088', 'This Little Life: Or, the Overachiever’s Journey to Appreciation & Contentment is a musical journey that moves in stages from ambition and perfectionism to joy and contentment. The recital features various styles, from musical theatre, to art song, and folk, and has several staged numbers and guest performers. With all luck it will make you laugh, cry, and leave you with a sense of appreciation for the small things in life, even in bleak winter!', 'February 1, 2025', 'February 1, 2025', null, 'Smith Auditorium','https://d1tvaw2qn8888b.cloudfront.net/cal-3c3dfcf0-8614-4143-950b-414809b5149c/square.jpg' ),
('Housing Contract for 2025-26 Opens - All Campuses', '/e/5528', 'Sign your housing contract to be eligible for housing in the Spring selection process.', 'February 3, 2025', 'February 3, 2025', null, 'Sign your housing contract to be eligible for housing in the Spring selection process.','' ),
('Last day to choose credit/no credit (CR/NC) grading for first half-semester classes (5 p.m. deadline)', '/e/4981', '', 'February 3, 2025', 'February 3, 2025', null, '','' ),
('Civic Commons', '/e/6177', 'Willamette’s Civic Commons brings together University community members in both Salem and Portland to showcase our existing work and inspire new collaborations around the Strategic Plan’s theme of democratic institutions and engaged democracy.', 'February 4, 2025', 'February 4, 2025', null, 'Willamette’s Civic Commons brings together University community members in both Salem and Portland to showcase our existing work and inspire new collaborations around the Strategic Plan’s theme of democratic institutions and engaged democracy.','https://d1tvaw2qn8888b.cloudfront.net/cal-c0e0b0ef-6dea-4d32-a267-7732e3900d79/square.jpg' ),
('Civic Commons', '/e/6178', 'Willamette’s Civic Commons brings together University community members in both Salem and Portland to showcase our existing work and inspire new collaborations around the Strategic Plan’s theme of democratic institutions and engaged democracy.', 'February 4, 2025', 'February 4, 2025', null, 'Willamette’s Civic Commons brings together University community members in both Salem and Portland to showcase our existing work and inspire new collaborations around the Strategic Plan’s theme of democratic institutions and engaged democracy.','https://d1tvaw2qn8888b.cloudfront.net/cal-8a5c426f-c683-44ed-b1b0-d734c143c679/square.jpg' ),
('Academic Success Workshop', '/e/6372', 'Willamette College invites undergraduate students on the Salem Campus to attend an academic success workshop.', 'February 4, 2025', 'February 4, 2025', null, '301','' ),
('No Job Experience? No Problem! Resume Workshop', '/e/6387', 'Learn how to create a quality resume even without having job or internship experience.', 'February 4, 2025', 'February 4, 2025', null, 'Digital Learning Studio - Ford 101','' ),
('Documentary Screening: No Place to Grow Old', '/e/6481', 'No Place To Grow Old is a powerful documentary that delves into the growing crisis of senior homelessness right here in Oregon.', 'February 4, 2025', 'February 4, 2025', null, '122','' ),
('Last day to withdraw from first half-semester classes (5 p.m. deadline)', '/e/4982', '', 'February 6, 2025', 'February 6, 2025', null, '','' ),
('Brenda Mallory: Common Connections', '/e/6476', 'Join us for the opening reception of Common Connections, a solo exhibition of works by Portland-based artist Brenda Mallory. This satellite exhibition of three works by Mallory is presented concurrently with The North Star Changes, a survey of works by Brenda Mallory at the Hallie Ford Museum of Art, curated by Rebecca Dobkins.', 'Feb  6, 2025', 'Feb  6, 2025', 'Apr  3, 2025', 'Ed Cauduro and Dane Nelson Collection Studies Lab','https://d1tvaw2qn8888b.cloudfront.net/cal-d79ca847-d162-492b-87f7-22f175fff073/square.jpg' ),
('February First Thursday at PNCA + North Park Blocks!', '/e/6179', 'Join us in the North Park Blocks in downtown Portland for exhibition openings, live music, refreshments and performances!', 'February 6, 2025', 'February 6, 2025', null, 'Join us in the North Park Blocks in downtown Portland for exhibition openings, live music, refreshments and performances!','https://d1tvaw2qn8888b.cloudfront.net/cal-0939c4b8-8314-46a0-a0ca-c8e29d842137/square.jpg' ),
('Eyes & Ears', '/e/6475', 'Visuals in Music 2020–2024, an exhibit curated by Bijan Berahimi on display from February 6 to April 3, 2025. Showcasing vinyl packaging, tour posters and merchandise with music videos co-curated by Noah Porter, the exhibition examines some of the most exciting visual work from the last four years.', 'Feb  6, 2025', 'Feb  6, 2025', 'Apr  3, 2025', 'Center Contemporary Art and Culture, The Dorothy Lemelson Innovation Studio, Ed Cauduro and Dane Nelson Collection Studies Lab','https://d1tvaw2qn8888b.cloudfront.net/cal-8aa13539-4068-4a92-8099-5183da60a25f/square.jpg' ),
('Know Your Rights Info Session: Navigating Immigration Policy', '/e/6480', 'Join us for an empowering and informative session designed to help you understand your rights as they relate to immigration policy.', 'February 6, 2025', 'February 6, 2025', null, 'Law 201','' ),
('HFMA First Friday Salem Art Walk', '/e/5947', 'Start your First Friday Art Walk at the Hallie Ford Museum of Art and get ready for an evening of fun and art in Salem!', 'February 7, 2025', 'February 7, 2025', null, 'Start your First Friday Art Walk at the Hallie Ford Museum of Art and get ready for an evening of fun and art in Salem!','https://d1tvaw2qn8888b.cloudfront.net/cal-ea86e69a-35db-4a1a-b531-7625ade089c3/square.jpg' ),
('Movie Night with the Alumni Office: Wicked', '/e/6472', 'Bring your blankets and sleepover energy for one of the most pop-u-lar movie musicals of the year!', 'February 7, 2025', 'February 7, 2025', null, 'Montag Den','https://d1tvaw2qn8888b.cloudfront.net/cal-1d62c0eb-f033-482c-87e2-2af5fd8615ef/square.jpg' ),
('Lunar New Year Celebration', '/e/6405', 'Join Sinophone Cultural Association (SCA) and the Global Cultural Studies Department in celebrating the Year of the Snake!', 'February 9, 2025', 'February 9, 2025', null, 'Cat Cavern','https://d1tvaw2qn8888b.cloudfront.net/cal-64304469-cad0-4597-bb37-de0bebeac05a/square.jpg' ),
('Last day for students to submit work to faculty for grading to replace grades of Incomplete (I) from the fall semester.', '/e/5406', '', 'February 11, 2025', 'February 11, 2025', null, '','' ),
('Canva Tips and Tricks!', '/e/6379', 'Come learn to use Canva for presentations, graphics, video editing, and poster-making with the DLS student specialists!', 'February 11, 2025', 'February 11, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-419a23cf-7df9-41fd-b8fc-edf790af032d/square.jpg' ),
('CAFES Grant Writing Workshop', '/e/6478', 'A joint grant writing workshop for CAS, Law, and MBA students', 'February 11, 2025', 'February 11, 2025', null, 'Autzen Conference Room','' ),
('LA Fire Relief Fundraiser', '/e/6477', 'Climate Action Alliance will be hosting a Valentine’s themed bake sale and craft fundraiser to raise money for 3 non-profit organizations that are helping LA recover from the recent wildfires. The fundraiser will take place on February 12th and 13th from 11:00 AM to 2:00 PM in Jackson Plaza. If you would like to donate crafts or baked goods, please DM: @wuclimateaction or Email: aebirchwright@willamette.edu.', 'February 12, 2025', 'February 12, 2025', null, 'Jackson Plaza','' ),
('Ready, Set, Search! | Job Search Workshop', '/e/6388', 'Join Career Development & The Writing Center in a collaboration to learn tips & tricks towards an approachable job search!', 'February 12, 2025', 'February 12, 2025', null, 'Writing Center','' ),
('Almost Something Public Reception', '/e/6444', 'A celebration of the accomplishments and work of the First Year MFA Candidates at PNCA', 'February 13, 2025', 'February 13, 2025', null, 'A celebration of the accomplishments and work of the First Year MFA Candidates at PNCA','https://d1tvaw2qn8888b.cloudfront.net/cal-6f8c7fc9-3daa-46c3-8a4c-da39b995ac34/square.jpg' ),
('PREVIEW: Far Away', '/e/6445', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 13, 2025', 'February 13, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-c62e2d49-21c3-462d-abf3-78dbafd12a3d/square.jpg' ),
('Last day for students to submit work to faculty for grading to replace grades of Incomplete (I) from the fall semester.', '/e/4983', '', 'February 14, 2025', 'February 14, 2025', null, '','' ),
('The Price of Metaphor:  Machine Minds and Missteps in Neuroscience', '/e/6359', 'A Lecture by Dr. Sama Ahmed
Professor of Psychology, University of Washington', 'February 14, 2025', 'February 14, 2025', null, '209','https://d1tvaw2qn8888b.cloudfront.net/cal-ed52fcf0-eb19-42fd-a43e-2619c1428ee8/square.jpg' ),
('OPENING NIGHT: Far Away', '/e/6446', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 14, 2025', 'February 14, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-d7e97038-8b8f-4363-a761-de51db71034d/square.jpg' ),
('Team Jigsaw Puzzling Competition', '/e/6364', 'How fast can you puzzle? Grab a team of 4 and join WEB at this fun event.', 'February 15, 2025', 'February 15, 2025', null, 'Montag Den','' ),
('Poetry Party at the Community Gardens', '/e/6479', 'ASWU, in conjunction with BSU, will be hosting an event exploring African-American ecology through poetry. Catering will be provided by Bon Appetit.', 'February 15, 2025', 'February 15, 2025', null, 'Community Gardens','' ),
('Junior Recital: Zach Martin & Hannah Rowe', '/e/6361', 'Students of Dr. Emily Stanek’s studio will be performing a combined recital. With music from 1700s to modern times, this recital is celebrating flute repertoire and the skills of both players as soloists and collaborative musicians.', 'February 15, 2025', 'February 15, 2025', null, 'Hudson Concert Hall','' ),
('Far Away', '/e/6447', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 15, 2025', 'February 15, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-cf230514-6ea6-4911-8917-7504e33836b3/square.jpg' ),
('MATINEE: Far Away', '/e/6452', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 16, 2025', 'February 16, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-d4e8cd8d-da6c-4997-b3c8-48ff8949e873/square.jpg' ),
('Senior Recital: Karina May', '/e/6362', 'All are welcome to this free event.', 'February 16, 2025', 'February 16, 2025', null, 'Hudson Concert Hall','' ),
('Annual Frost Lecture with Professor Seth Rockman', '/e/6402', 'Annual Frost Lecture with Professor Seth Rockman
Plantation Goods: A Material History of American Slavery
Monday February 17, 2025
7:30pm', 'February 17, 2025', 'February 17, 2025', null, 'John C. Paulus Lecture Hall, room 201','https://d1tvaw2qn8888b.cloudfront.net/cal-ba88949a-d942-47b5-afe9-6ede5e2d70e3/square.jpg' );

INSERT INTO events (title, link, description, pub_date, event_start_date, event_end_date, location, image_url) VALUES 
('Grace Goudy Distinguished Artist Series: Cantores in Ecclesia Vocal Ensemble', '/e/6090', 'Cantores in Ecclesia, directed by Blake Applegate, is a specialized vocal
ensemble dedicated to the preservation and promotion of Gregorian chant and
sacred polyphony in liturgical context within the Latin Mass of the
Catholic Church.', 'February 19, 2025', 'February 19, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-3f318597-0769-449a-b542-205d0422e026/square.jpg' ),
('Far Away', '/e/6448', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 19, 2025', 'February 19, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-02cd4c8c-6b2e-42cd-86bc-ab6ad4365c30/square.jpg' ),
('Building Resilience During the Job Search Workshop', '/e/6471', 'Join Career Development for a helpful workshop to teach ways to stay strong through the job search!', 'February 20, 2025', 'February 20, 2025', null, 'Renjen Center','' ),
('Heritage Club at Willamette’s Far Away Performance', '/e/6482', 'Join fellow alumni greater than 50 years out from graduation for this exceptional performance and a pre-performance gathering at the Taproot Old Mill Café.', 'February 20, 2025', 'February 20, 2025', null, 'Pelton Theatre','' ),
('Far Away', '/e/6449', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 20, 2025', 'February 20, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-4b9b055f-9495-4250-a86c-f1cf9fc7329e/square.jpg' ),
('Mindful Yoga', '/e/6365', 'Join Willamette Alum Mikki Trowbridge as she leads a mindful yoga session.', 'February 21, 2025', 'February 21, 2025', null, 'Multi-purpose Room 108','' ),
('Willamette Graduate Open House', '/e/6483', 'Join us to connect with the alumni community, discuss career advancement options, and explore the new EcoTrust building.  Faculty will host informational sessions about Willamette’s Master’s in Data Science, Master’s in Computer Science, and MBA programs.Food will be served at a reception where you can mingle with Willamette alumni, faculty, and trustees.', 'February 21, 2025', 'February 21, 2025', null, 'Food will be served at a reception where you can mingle with Willamette alumni, faculty, and trustees.','' ),
('Far Away', '/e/6450', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 21, 2025', 'February 21, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-7a1f4b84-e59c-4919-9a64-b5fa34f74ca0/square.jpg' ),
('MATINEE: Far Away', '/e/6453', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 22, 2025', 'February 22, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-947392f3-df44-4393-9736-9d5e7983a1dc/square.jpg' ),
('Far Away', '/e/6451', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 22, 2025', 'February 22, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-e7b51080-c959-46f4-924f-f56fd0dcdc19/square.jpg' ),
('MATINEE: Far Away', '/e/6454', 'Willamette University Theatre presents a modern fable about nature at war with herself.', 'February 23, 2025', 'February 23, 2025', null, 'Main Stage','https://d1tvaw2qn8888b.cloudfront.net/cal-46adfbdf-0aef-44e6-b631-5042c53da83e/square.jpg' ),
('Winter Choral Concert', '/e/6092', '', 'February 23, 2025', 'February 23, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-1bc25a59-1902-4d25-b06e-562cf73a688f/square.jpg' ),
('Last day to choose credit/no credit (CR/NC) grading for full semester classes (5 p.m. deadline)', '/e/4985', '', 'February 24, 2025', 'February 24, 2025', null, '','' ),
('Doughnuts with the Deans of PNCA', '/e/6442', 'Join PNCA Dean Cole and Dean of Student Potts for monthly casual conversations. These informal gatherings offer a relaxed setting where you can drop by, grab a cup of coffee, a doughnut, and chat.', 'February 24, 2025', 'February 24, 2025', null, 'Hammer Boardroom','https://d1tvaw2qn8888b.cloudfront.net/cal-7062f9b4-5e03-4204-8b54-69e9b23a717e/square.jpg' ),
('Spring In-Service', '/e/4984', '', 'February 25, 2025', 'February 25, 2025', null, '','' ),
('The Immigrant Story Pre Conversation', '/e/6390', '', 'February 25, 2025', 'February 25, 2025', null, 'Cone Chapel','' ),
('Video & Audio editing!', '/e/6380', 'Learn to use the free video & audio editing programs available to you with the DLS student specialists!', 'February 26, 2025', 'February 26, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-af21819e-bf91-446a-bb77-ac89a5bffe1d/square.jpg' ),
('Movie Night with the Alumni Office: Labyrinth', '/e/6473', 'Through dangers untold and hardships unnumbered…come see this iconic 80s magic film complete with Jim Henson muppets and David Bowie!', 'February 27, 2025', 'February 27, 2025', null, 'Mediatheque','https://d1tvaw2qn8888b.cloudfront.net/cal-5460dd03-0564-4f07-bcf2-7cd42c02829b/square.jpg' ),
('CASA/AIA 2025 Spring Lecture series with Dr. Kiersten Neumann', '/e/6404', 'CASA/AIA 2025 Spring Lecture series with Dr. Kiersten Neumann (2024-2025 AIA Kershaw Lecturer). From Ancient Quarries to New Inquiries: Exhibiting the ISAC Museum’s Roman Sculpture Collection in an Age of GreaterTransparency', 'February 27, 2025', 'February 27, 2025', null, 'John C. Paulus Lecture Hall-Room 201','https://d1tvaw2qn8888b.cloudfront.net/cal-d5c95298-2866-4314-bf9e-059c7ca34c66/square.jpg' ),
('Willamette Singers and Jazz Combos with special guest Garrett Baxter', '/e/6091', 'Join us for an evening of jazz where the Willamette Singers will debut a new piece by Garrett Baxter, who is also performing with the Singers.', 'February 27, 2025', 'February 27, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-eb2cc97d-4ed9-4412-ba38-832054d2b606/square.jpg' ),
('Midterm grades due', '/e/4989', '', 'February 28, 2025', 'February 28, 2025', null, '','' ),
('Launch Your Job Search Workshop', '/e/6389', 'Come join Career Development to learn some best practices towards getting your job search off the ground!', 'February 28, 2025', 'February 28, 2025', null, 'Collins 323','' ),
('Spring Craft Fair Day 1', '/e/6366', 'Check out and purchase some amazing work from your Willamette community!', 'February 28, 2025', 'February 28, 2025', null, 'Montag Den','' ),
('Spring Craft Fair Day 2', '/e/6367', 'Check out and purchase some amazing work from your Willamette community!', 'March 1, 2025', 'March 1, 2025', null, 'Montag Den','' ),
('Faculty Recital: James Miley with Jazz Ensemble', '/e/6184', '', 'March 2, 2025', 'March 2, 2025', null, 'Rogers Rehearsal Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-481b7e41-101b-447c-99f4-f3ec9506dbd4/square.jpg' ),
('Last day of first half-semester classes (final exams administered in class)', '/e/4987', '', 'March 3, 2025', 'March 3, 2025', null, '','' ),
('First day of second half-semester classes', '/e/4988', '', 'March 4, 2025', 'March 4, 2025', null, '','' ),
('Spruce Up Your Slides & Presentations!', '/e/6392', 'Get your SSRD presentation ready with the Digital Learning Studio student specialists!', 'March 4, 2025', 'March 4, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-f5a3aaf3-954b-42cf-8df9-e28c7a0c754c/square.jpg' ),
('The Immigrant Story Live', '/e/6400', '', 'March 4, 2025', 'March 4, 2025', null, 'Hudson Hall','' ),
('Registration for Summer Courses', '/e/4986', '', 'March 5, 2025', 'March 5, 2025', null, '','' ),
('Academic Success Workshop - Embracing Progress: Overcoming Perfectionism', '/e/6422', 'In this transformative workshop we’ll explore how to over barriers impacting your creativity and academic success. We’ll look at the root of perfectionism and learn tools to shift that mindset.', 'March 5, 2025', 'March 5, 2025', null, '511','' ),
('Academic Success Workshop - Embracing Progress: Overcoming Perfectionism', '/e/6423', 'In this transformative workshop we’ll explore how to over barriers impacting your creativity and academic success. We’ll look at the root of perfectionism and learn tools to shift that mindset.', 'March 6, 2025', 'March 6, 2025', null, '511','' ),
('Perfect your Project Poster', '/e/6410', 'Work on your SSRD project poster with the DLS student specialists!', 'March 6, 2025', 'March 6, 2025', null, 'Ford 101','https://d1tvaw2qn8888b.cloudfront.net/cal-6b1cbb5a-f027-4422-913a-ba3ac25670e2/square.jpg' ),
('Perfect your project poster!', '/e/6413', 'Work on your SSRD project poster with the DLS student specialists!', 'March 6, 2025', 'March 6, 2025', null, 'Digital Leraning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-1e104d4b-9ed3-4a57-9ec0-c1d5bebd7ec6/square.jpg' ),
('March First Thursday at PNCA + North Park Blocks!', '/e/6180', 'Join us in the North Park Blocks for exhibition openings, live music, refreshments and performances!', 'March 6, 2025', 'March 6, 2025', null, 'Join us in the North Park Blocks for exhibition openings, live music, refreshments and performances!','https://d1tvaw2qn8888b.cloudfront.net/cal-87d84b27-a4a9-4a6d-b9b4-ca8a708c7946/square.jpg' ),
('Movie Night with the Alumni Office: Moana', '/e/6474', 'The pool calls you! Jump right on in and enjoy this Disney-Pixar classic, complete with floatation devices so you can focus on singing along to your heart’s content.', 'March 8, 2025', 'March 8, 2025', null, 'Sparks Pool','https://d1tvaw2qn8888b.cloudfront.net/cal-260da8df-b2e3-4655-b326-11eeb37581ba/square.jpg' ),
('Fete des Femmes', '/e/6093', 'In its fourth annual tribute to International Women’s Day, Willamette Music brings together an extraordinary array of performances from around the globe and through the decades, all in celebration of countless contributions women have made to the world of music. Join us in celebrating the timeless voices and talents that have paved the way for centuries of female musicians and artists.', 'March 8, 2025', 'March 8, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-3e6b53a4-901e-4a66-a30a-ec902ca634a8/square.jpg' ),
('iMovie Tips & Tricks!', '/e/6381', 'Interested in getting better at iMovie? Learn more with the DLS student specialists!', 'March 11, 2025', 'March 11, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-3874c05e-ee41-4570-aad3-5471191b567f/square.jpg' ),
('Perfect your project poster!', '/e/6416', 'Work on your SSRD project poster with the DLS student specialists!', 'March 11, 2025', 'March 11, 2025', null, 'Digital Learning Studio Ford 101','https://d1tvaw2qn8888b.cloudfront.net/cal-117d5a8c-9ded-43a8-9f11-8c6946524e3b/square.jpg' ),
('The Immigrant Story Post Conversation', '/e/6391', '', 'March 11, 2025', 'March 11, 2025', null, 'Cone Chapel','' ),
('Last day to withdraw from full-semester classes* (5 p.m. deadline)', '/e/5821', '', 'March 12, 2025', 'March 12, 2025', null, '','' ),
('Last day to withdraw from full-semester classes* (full withdrawal only) (5 p.m. deadline)', '/e/4994', '', 'March 12, 2025', 'March 12, 2025', null, '','' ),
('Last day to withdraw from full-semester classes (5 p.m. deadline)', '/e/5840', '', 'March 13, 2025', 'March 13, 2025', null, '','' ),
('Spruce up your slides & presentation!', '/e/6393', 'Get your slides and presentations ready for SSRD with the DLS student specialists', 'March 13, 2025', 'March 13, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-6093fead-488c-4661-899c-38272f29193d/square.jpg' ),
('Last day to withdraw from full-semester classes (5 p.m. deadline)', '/e/4992', '', 'March 14, 2025', 'March 14, 2025', null, '','' ),
('Last day to withdraw from full-semester classes* (full withdrawal only) (5 p.m. deadline)', '/e/4993', '', 'March 14, 2025', 'March 14, 2025', null, '','' ),
('Dramatic Vocal Arts Presents The Little Prince', '/e/6185', '', 'March 15, 2025', 'March 15, 2025', null, 'Smith Auditorium','https://d1tvaw2qn8888b.cloudfront.net/cal-6f80f254-4af1-41eb-8543-75de0d0c4ea1/square.jpg' ),
('Dramatic Vocal Arts Presents The Little Prince', '/e/6186', '', 'March 16, 2025', 'March 16, 2025', null, 'Smith Auditorium','https://d1tvaw2qn8888b.cloudfront.net/cal-142abf9e-4880-4684-8bdc-5ed76ea5ca51/square.jpg' ),
('Last day to withdraw from full-semester classes (5 p.m. deadline)', '/e/4991', '', 'March 17, 2025', 'March 17, 2025', null, '','' ),
('Last day to add/drop or choose Audit (AUD) grading for second half-semester classes (5 p.m. deadline)', '/e/4998', '', 'March 17, 2025', 'March 17, 2025', null, '','' ),
('Spruce up your slides & presentation!', '/e/6395', 'Get your slides and presentations ready for SSRD with the DLS student specialists', 'March 17, 2025', 'March 17, 2025', null, 'Ford Hall 101 - Digital Learning Studio','https://d1tvaw2qn8888b.cloudfront.net/cal-8d76fd3b-9121-483a-b490-2077b8498378/square.jpg' ),
('Jazz Collective feat. Patty Darling', '/e/6187', '', 'March 18, 2025', 'March 18, 2025', null, 'Hudson Concert Hall','https://d1tvaw2qn8888b.cloudfront.net/cal-d5a96633-2880-4070-bc2d-e7411c07478b/square.jpg' ),
('Perfect your project poster!', '/e/6412', 'Work on your SSRD project poster with the DLS student specialists!', 'March 19, 2025', 'March 19, 2025', null, 'Ford 101','https://d1tvaw2qn8888b.cloudfront.net/cal-1fbdde6f-ca76-4d2d-9988-3641bbd3cc76/square.jpg' ),
('Last Board Meal - Dinner - Salem Campus', '/e/5529', 'Last meal before Spring Break.', 'March 21, 2025', 'March 21, 2025', null, 'Last meal before Spring Break.','' ),
('Spring Break - All Campuses', '/e/5531', 'Residence Halls are open during Spring Break.', 'Mar 24, 2025', 'Mar 24, 2025', 'Mar 28, 2025', 'Residence Halls are open during Spring Break.','' ),
('Spring Break', '/e/4999', '', 'Mar 24, 2025', 'Mar 24, 2025', 'Mar 28, 2025', '','' ),
('Dining Services - Salem Campus', '/e/5716', '', 'Mar 24, 2025', 'Mar 24, 2025', 'Mar 28, 2025', '','' ),
('Meal Plans Resume - Salem Campus', '/e/5532', 'Meal Plans resume with dinner.', 'March 30, 2025', 'March 30, 2025', null, 'Meal Plans resume with dinner.','' ),
('Last day to choose credit/no credit (CR/NC) grading for second half-semester classes (5 p.m. deadline)', '/e/5000', '', 'March 31, 2025', 'March 31, 2025', null, '','' ),
('Perfect your Project Poster!', '/e/6415', 'Work on your SSRD project poster with the DLS student specialists!', 'March 31, 2025', 'March 31, 2025', null, 'Ford 101','https://d1tvaw2qn8888b.cloudfront.net/cal-2172168e-b31d-4b5b-b0f1-8a51af77d196/square.jpg' ),
('Late Stay Request Process Opens - Salem Campus', '/e/5718', '', 'April 1, 2025', 'April 1, 2025', null, '','' );



INSERT INTO tags (name) VALUES 
(''),
('Hallie Ford Museum of Art'),
('Salem Campus'),
('Mary Stuart Rogers Music Center'),
('Waller Hall'),
('Ford Hall'),
('Delta Gamma'),
('Arlene and Harold Schnitzer Center for Art and Design'),
('PNCA Campus'),
('Other'),
('Putnam University Center'),
('Virtual Event'),
('Baxter Hall'),
('Alpha Chi Omega'),
('Eaton Hall'),
('G. Herbert Smith Auditorium'),
('Truman Wesley Collins Legal Center'),
('Outdoors'),
('M. Lee Pelton Theatre'),
('Lestle J. Sparks Center'),
('EcoTrust Building'),
('Collins Science Center')
;


INSERT INTO event_tags (event_id, tag_id) VALUES 
((SELECT id FROM events WHERE link = '/e/4974'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5309'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4971'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4968'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5946'), 
                  (SELECT id FROM tags WHERE name = 'Hallie Ford Museum of Art')),
((SELECT id FROM events WHERE link = '/e/5946'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4970'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5715'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5712'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5525'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6374'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6374'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6435'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4973'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4978'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6360'), 
                  (SELECT id FROM tags WHERE name = 'Waller Hall')),
((SELECT id FROM events WHERE link = '/e/6360'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6386'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6386'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6369'), 
                  (SELECT id FROM tags WHERE name = 'Delta Gamma')),
((SELECT id FROM events WHERE link = '/e/6369'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6378'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6378'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/4976'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6370'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6370'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6385'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6385'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6408'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6408'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6440'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6394'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6394'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6382'), 
                  (SELECT id FROM tags WHERE name = 'Virtual Event')),
((SELECT id FROM events WHERE link = '/e/6411'), 
                  (SELECT id FROM tags WHERE name = 'Baxter Hall')),
((SELECT id FROM events WHERE link = '/e/6411'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5527'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6383'), 
                  (SELECT id FROM tags WHERE name = 'Other'));


              
INSERT INTO event_tags (event_id, tag_id) VALUES     
((SELECT id FROM events WHERE link = '/e/6383'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6409'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6409'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6406'), 
                  (SELECT id FROM tags WHERE name = 'Alpha Chi Omega')),
((SELECT id FROM events WHERE link = '/e/6406'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6436'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4977'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6363'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6363'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6443'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6443'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6371'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6371'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6384'), 
                  (SELECT id FROM tags WHERE name = 'Virtual Event')),
((SELECT id FROM events WHERE link = '/e/6420'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6420'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6398'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6398'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6421'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6421'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6368'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6368'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6146'), 
                  (SELECT id FROM tags WHERE name = 'Eaton Hall')),
((SELECT id FROM events WHERE link = '/e/6146'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6465'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6465'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4980'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6407'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6407'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6088'), 
                  (SELECT id FROM tags WHERE name = 'G. Herbert Smith Auditorium')),
((SELECT id FROM events WHERE link = '/e/6088'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5528'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4981'), 
                  (SELECT id FROM tags WHERE name = ''));


INSERT INTO event_tags (event_id, tag_id) VALUES 
((SELECT id FROM events WHERE link = '/e/6177'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6177'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6178'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6178'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6372'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6372'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6387'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6387'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6481'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6481'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4982'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6476'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6476'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6179'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6179'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6475'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6475'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6480'), 
                  (SELECT id FROM tags WHERE name = 'Truman Wesley Collins Legal Center')),
((SELECT id FROM events WHERE link = '/e/6480'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5947'), 
                  (SELECT id FROM tags WHERE name = 'Hallie Ford Museum of Art')),
((SELECT id FROM events WHERE link = '/e/5947'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6472'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6472'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6405'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6405'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5406'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6379'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6379'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6478'), 
                  (SELECT id FROM tags WHERE name = 'Putnam University Center')),
((SELECT id FROM events WHERE link = '/e/6478'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6477'), 
                  (SELECT id FROM tags WHERE name = 'Outdoors')),
((SELECT id FROM events WHERE link = '/e/6477'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6388'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6388'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6444'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6445'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6445'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4983'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6359'), 
                  (SELECT id FROM tags WHERE name = 'Eaton Hall')),
((SELECT id FROM events WHERE link = '/e/6359'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6446'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6446'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6364'), 
                  (SELECT id FROM tags WHERE name = 'Baxter Hall')),
((SELECT id FROM events WHERE link = '/e/6364'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6479'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6479'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6361'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6361'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6447'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6447'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6452'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre'));


INSERT INTO event_tags (event_id, tag_id) VALUES                   
((SELECT id FROM events WHERE link = '/e/6452'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6362'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6362'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6402'), 
                  (SELECT id FROM tags WHERE name = 'Truman Wesley Collins Legal Center')),
((SELECT id FROM events WHERE link = '/e/6402'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6090'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6090'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6448'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6448'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6471'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6471'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6482'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6482'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6449'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6449'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6365'), 
                  (SELECT id FROM tags WHERE name = 'Lestle J. Sparks Center')),
((SELECT id FROM events WHERE link = '/e/6365'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6483'), 
                  (SELECT id FROM tags WHERE name = 'EcoTrust Building')),
((SELECT id FROM events WHERE link = '/e/6450'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6450'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6453'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6453'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6451'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6451'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6454'), 
                  (SELECT id FROM tags WHERE name = 'M. Lee Pelton Theatre')),
((SELECT id FROM events WHERE link = '/e/6454'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6092'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6092'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4985'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6442'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6442'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/4984'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6390'), 
                  (SELECT id FROM tags WHERE name = 'Waller Hall')),
((SELECT id FROM events WHERE link = '/e/6390'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6380'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6380'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6473'), 
                  (SELECT id FROM tags WHERE name = 'Other')),
((SELECT id FROM events WHERE link = '/e/6473'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6404'), 
                  (SELECT id FROM tags WHERE name = 'Truman Wesley Collins Legal Center')),
((SELECT id FROM events WHERE link = '/e/6404'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6091'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6091'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4989'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6389'), 
                  (SELECT id FROM tags WHERE name = 'Collins Science Center')),
((SELECT id FROM events WHERE link = '/e/6389'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6366'), 
                  (SELECT id FROM tags WHERE name = 'Baxter Hall')),
((SELECT id FROM events WHERE link = '/e/6366'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6367'), 
                  (SELECT id FROM tags WHERE name = 'Baxter Hall')),
((SELECT id FROM events WHERE link = '/e/6367'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6184'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6184'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4987'), 
                  (SELECT id FROM tags WHERE name = ''));


INSERT INTO event_tags (event_id, tag_id) VALUES                   
((SELECT id FROM events WHERE link = '/e/4988'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6392'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6392'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6400'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6400'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4986'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6422'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6422'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6423'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6423'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6410'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6410'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6413'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6413'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6180'), 
                  (SELECT id FROM tags WHERE name = 'Arlene and Harold Schnitzer Center for Art and Design')),
((SELECT id FROM events WHERE link = '/e/6180'), 
                  (SELECT id FROM tags WHERE name = 'PNCA Campus')),
((SELECT id FROM events WHERE link = '/e/6474'), 
                  (SELECT id FROM tags WHERE name = 'Lestle J. Sparks Center')),
((SELECT id FROM events WHERE link = '/e/6474'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6093'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6093'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6381'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6381'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6416'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6416'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6391'), 
                  (SELECT id FROM tags WHERE name = 'Waller Hall')),
((SELECT id FROM events WHERE link = '/e/6391'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5821'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4994'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5840'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6393'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6393'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4992'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4993'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6185'), 
                  (SELECT id FROM tags WHERE name = 'G. Herbert Smith Auditorium')),
((SELECT id FROM events WHERE link = '/e/6185'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6186'), 
                  (SELECT id FROM tags WHERE name = 'G. Herbert Smith Auditorium')),
((SELECT id FROM events WHERE link = '/e/6186'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/4991'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4998'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6395'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6395'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6187'), 
                  (SELECT id FROM tags WHERE name = 'Mary Stuart Rogers Music Center')),
((SELECT id FROM events WHERE link = '/e/6187'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/6412'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6412'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5529'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5531'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/4999'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5716'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5532'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/5000'), 
                  (SELECT id FROM tags WHERE name = '')),
((SELECT id FROM events WHERE link = '/e/6415'), 
                  (SELECT id FROM tags WHERE name = 'Ford Hall')),
((SELECT id FROM events WHERE link = '/e/6415'), 
                  (SELECT id FROM tags WHERE name = 'Salem Campus')),
((SELECT id FROM events WHERE link = '/e/5718'), 
                  (SELECT id FROM tags WHERE name = ''));
